# config/west.yml
manifest:
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk
      revision: main
      import: app/west.yml
    - name: zmk-mouse-gesture
      url: https://github.com/kot149/zmk-mouse-gesture
      revision: main
  self:
    path: config
